# Don't edit the `bin` list manually! It is updated by `rustlings dev update`
bin = [
  { name = "building_the_sdk_just_a_moment_please", path = "exercises/building_the_sdk_just_a_moment_please.rs" },
  { name = "your_first_plugin", path = "exercises/your_first_plugin.rs" },
  { name = "your_first_plugin_sol", path = "solutions/your_first_plugin.rs" },
]

[package]
name = "exercises"
edition = "2021"
# Don't publish the exercises on crates.io!
publish = false

[dependencies]
falco_plugin = { git = "https://github.com/falcosecurity/plugin-sdk-rs" }